#pragma once

enum DEVICE_TYPE_ENUM {
	FOUR_RELAY_OUT = 0xFB,
	RTD = 0xFC,
	TEN_VOLT = 0xFD,
	FOUR_TWENTY_MILLIAMP = 0xFE,
	INTERNAL = 0xFF,
	EIGHT_BIT_TEMPERATURE = 0x10,
	TWELVE_BIT_TEMPERATURE = 0x28
};
